// <auto-generated />
namespace Mvc4App.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddStudent : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddStudent));
        
        string IMigrationMetadata.Id
        {
            get { return "202103141103315_AddStudent"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
